// src/routes/(main)/_components/why-me/why-me.svelte
<script lang="ts">
	import Card from '$lib/components/ui/card.svelte';
	import Badge from '$lib/components/ui/badge.svelte';
	import { Clock, LucideType, MessageSquare, Search } from 'lucide-svelte';

	interface Card {
		title: string;
		description: string;
		icon: typeof LucideType;
	}

	const cards: Card[] = [
		{
			title: 'Efficient Workflow',
			description:
				'Streamlined developing process for rapid deliver without compromising quality or detail.',
			icon: Clock
		},
		{
			title: 'Collaborative Process',
			description:
				'I work closely with you, integrating your feedback to create fantastic softwares and amazing experiences',
			icon: MessageSquare
		},
		{
			title: 'Attention to Detail',
			description:
				'Meticulous attention to everything, ensuring a polished and cohesive final application that impresses.',
			icon: Search
		}
	];
</script>

{#snippet whyMeCard(title: string, text: string, Icon: typeof LucideType)}
	<Card class="space-y-6">
		<div
			class="flex size-12 items-center justify-center rounded-lg border border-light-black bg-lighter-black"
		>
			<Icon />
		</div>
		<h3 class="text-xl">{title}</h3>
		<p class="text-[16px] text-gray">{text}</p>
	</Card>
{/snippet}

<section id="why-me" class="container flex flex-col items-center justify-center gap-10 py-16">
	<Badge>Why me?</Badge>

	<h2 class="px-2 text-center text-[32px] leading-none lg:px-0 lg:text-5xl">
		I create epic apps that <span class="text-gray">spark</span>
		your imagination!
	</h2>

	<div class="grid gap-8 md:grid-cols-3">
		{#each cards as card (card.title)}
			{@render whyMeCard(card.title, card.description, card.icon)}
		{/each}
	</div>
</section>

// app/(main)/_components/why-me/why-me.tsx
import Icon from '@/components/icon/icon';
import Badge from '@/components/ui/badge/badge';
import WhyMeCard from './why-me-card';

export default function WhyMe() {
  return (
    <section className='flex flex-col items-center justify-center gap-10 py-16'>
      <Badge>Why me?</Badge>
      <h2 className='px-2 text-center text-[32px] leading-none lg:px-0 lg:text-5xl'>
        I create epic apps that <span className='text-[--gray]'>spark</span>{' '}
        your imagination!
      </h2>
      <section className='grid gap-8 md:grid-cols-3'>
        <WhyMeCard icon={<Icon.Watch />} title='Efficient Workflow'>
          Streamlined developing process for rapid deliver without compromising
          quality or detail.
        </WhyMeCard>
        <WhyMeCard title='Collaborative Process' icon={<Icon.Chat />}>
          I work closely with you, integrating your feedback to create fantastic
          softwares and amazing experiences
        </WhyMeCard>
        <WhyMeCard title='Attention to Detail' icon={<Icon.Search />}>
          Meticulous attention to everything, ensuring a polished and cohesive
          final application that impresses.
        </WhyMeCard>
      </section>
    </section>
  );
}
