// app/(main)/_components/hero-section/hero-metalic-flower.tsx
import Image from 'next/image';
import * as motion from 'motion/react-client';

export function HeroMetalicFlower() {
  return (
    <section className='relative -z-50 shadow-2xl'>
      <div id='metalic-flower-wrapper'>
        <motion.section
          initial={{ rotate: -65, y: 30 }}
          animate={{ y: 0, rotate: 0, scale: 1, opacity: 1 }}
          transition={{ duration: 1.5 }}
          className='opacity-0'
        >
          <Image
            decoding='async'
            width={500}
            height={500}
            sizes='500'
            src='/metalic-flower.webp'
            alt='Grey-metallic-flower-shaped-object'
            className='object-cover'
          ></Image>
          <div className='absolute top-0 -z-50 w-full rounded-full bg-white py-64 opacity-10 blur-3xl'></div>
        </motion.section>
      </div>
      <div className='from-almost-black absolute top-[40%] z-50 h-[600px] w-full bg-gradient-to-tr to-black opacity-85 blur-3xl'></div>
      <div className='from-almost-black absolute top-[80%] z-50 h-[600px] w-full bg-gradient-to-tr to-black blur-3xl'></div>
    </section>
  );
}

// src/routes/(main)/_components/hero/hero-metalic-flower.svelte
<script lang="ts">
	import { Spring } from 'svelte/motion';

	let wrapper: HTMLElement;

	let scrollY = $state(0);

	let isReady = $state(false);

	const motion = new Spring({ y: 0, r: 0 }, { stiffness: 0.05, damping: 0.7 });

	$effect(() => {
		if (wrapper) {
			if (!isReady) {
				isReady = true;
			}

			const top = wrapper.getBoundingClientRect().top + scrollY - motion.current.y;

			const p = Math.max(0, Math.min(1, (scrollY - (top - 500)) / 1300));

			motion.target = { y: p * 230, r: p * 45 };
		}
	});
</script>

<svelte:window bind:scrollY />

<section class="relative -z-50 shadow-2xl select-none">
	<div
		bind:this={wrapper}
		style:transform="translateY({motion.current.y}px) rotate({motion.current.r}deg)"
	>
		<div
			class="transition-all duration-1500 ease-[cubic-bezier(0.25,1,0.5,1)] {isReady
				? 'translate-y-0 scale-100 rotate-0 opacity-100'
				: 'translate-y-7.5 -rotate-30 opacity-20'}"
		>
			<img
				src="images/metalic-flower.webp"
				alt="Grey-metallic-flower-shaped-object"
				class="size-90 object-cover md:size-125"
			/>
			<div
				class="absolute top-0 -z-50 w-full rounded-full bg-white py-64 opacity-10 blur-3xl"
			></div>
		</div>
	</div>

	<div
		class="absolute top-[40%] z-50 h-150 w-full bg-linear-to-tr from-almost-black to-black opacity-85 blur-3xl"
	></div>
	<div
		class="absolute top-[80%] z-50 h-150 w-full bg-linear-to-tr from-almost-black to-black blur-3xl"
	></div>
</section>
