// src/lib/components/ui/github-link.svelte
<script lang="ts">
	import favicon from '$lib/assets/favicon.ico';

	let { class: className }: { class?: string } = $props();
</script>

<a
	href="https://github.com/tahasadough"
	target="_blank"
	class="z-60 flex items-center gap-2 {className}"
>
	<img src={favicon} alt="profile" class="size-6.25 rounded-full object-cover" />
	<h2 class="font-bold">Taha Sadough</h2>
</a>

// components/github-link/github-link.tsx
import Link from 'next/link';
import Image from 'next/image';

export default function GitHubLink() {
  return (
    <Link
      href='https://github.com/tahasadough'
      target='_blank'
      className='flex items-center gap-2'
    >
      <Image
        src='/favicon.ico'
        width={25}
        height={25}
        alt='profile-image'
        className='rounded-full object-cover'
      />
      <h2 className='font-bold'>Taha Sadough</h2>
    </Link>
  );
}
